import Document, { Head, Html, Main, NextScript } from "next/document";

class MyDocument extends Document {
  render() {
    return (
      <Html lang="en">
        <Head>
          <link rel="icon" href="/favicon.ico" />
          <meta
            name="description"
            content="Generate your next Twitter bio in seconds."
          />
          <meta property="og:site_name" content="cookingai.com" />
          <meta
            property="og:description"
            content="Generate your next Twitter bio in seconds."
          />
          <meta property="og:title" content="Cooking AI - Your food ideas generated by AI" />
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content="Cooking AI" />
          <meta
            name="twitter:description"
            content="Generate your next food idea in seconds."
          />
          <meta
            property="og:image"
            content="https://cookingai.com/og-image.png"
          />
          <meta
            name="twitter:image"
            content="https://cookingai.com/og-image.png"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
